import { calculateMatches } from "@/lib/matching";
import type { CandidateProfile, DemoState, Job } from "@/lib/types";

const jobs: Job[] = [
  {
    id: "job-1",
    reference: "JOB-2407",
    organizationId: "org-1",
    companyName: "Harbor Foods Private Limited",
    title: "Restaurant Service Associate",
    category: "Hospitality",
    city: "Kochi",
    workArea: "Edappally",
    workMode: "On-site",
    employmentType: "Full-time",
    shift: "Day",
    salaryMin: 18000,
    salaryMax: 24000,
    openings: 6,
    experienceMin: 1,
    education: "Higher Secondary or equivalent",
    description: "Support guests, coordinate orders, and maintain a welcoming dining area for a busy restaurant team.",
    employeeSummary: "Support guests, coordinate orders, and keep the service area welcoming. The verified employer and exact worksite are shared only after admin clearance.",
    requiredSkills: ["Customer service", "POS billing"],
    preferredSkills: ["Food safety", "English"],
    requiredDocuments: ["Government ID", "Resume"],
    screeningQuestions: ["Can you work a rotating weekend shift?"],
    employeeScreeningQuestions: ["Can you work the listed day shift and occasional weekends?"],
    interviewAvailability: "Weekdays, 10:00 AM–4:00 PM",
    status: "approved",
    createdAt: "2026-07-14T09:30:00.000Z",
  },
  {
    id: "job-2",
    reference: "JOB-2408",
    organizationId: "org-1",
    companyName: "Harbor Foods Private Limited",
    title: "Kitchen Helper",
    category: "Hospitality",
    city: "Kochi",
    workArea: "Kakkanad",
    workMode: "On-site",
    employmentType: "Full-time",
    shift: "Flexible",
    salaryMin: 16000,
    salaryMax: 20000,
    openings: 4,
    experienceMin: 0,
    education: "No formal requirement",
    description: "Prepare ingredients, keep work areas organized, and support the kitchen team during service.",
    employeeSummary: "Help prepare ingredients, keep work areas organized, and support day-to-day kitchen operations.",
    requiredSkills: ["Food safety"],
    preferredSkills: ["Teamwork"],
    requiredDocuments: ["Government ID"],
    screeningQuestions: ["Are you comfortable working in a commercial kitchen?"],
    employeeScreeningQuestions: ["Are you comfortable with a flexible shift in a commercial kitchen role?"],
    interviewAvailability: "Monday–Saturday, 11:00 AM–3:00 PM",
    status: "submitted",
    createdAt: "2026-07-16T04:20:00.000Z",
  },
  {
    id: "job-3",
    reference: "JOB-2409",
    organizationId: "org-1",
    companyName: "Harbor Foods Private Limited",
    title: "Delivery Coordinator",
    category: "Logistics",
    city: "Kochi",
    workArea: "Vyttila",
    workMode: "On-site",
    employmentType: "Full-time",
    shift: "Evening",
    salaryMin: 20000,
    salaryMax: 27000,
    openings: 2,
    experienceMin: 1,
    education: "Higher Secondary or equivalent",
    description: "Coordinate delivery partners, confirm dispatches, and resolve basic order issues.",
    employeeSummary: "Coordinate dispatch activity, confirm deliveries, and help resolve routine order issues.",
    requiredSkills: ["Customer service", "Route planning"],
    preferredSkills: ["POS billing"],
    requiredDocuments: ["Government ID", "Resume"],
    screeningQuestions: ["Do you have experience coordinating delivery partners?"],
    employeeScreeningQuestions: ["Do you have experience coordinating deliveries or dispatch work?"],
    interviewAvailability: "Weekdays after 2:00 PM",
    status: "under_review",
    createdAt: "2026-07-15T08:10:00.000Z",
  },
];

const candidate: CandidateProfile = {
  id: "candidate-1",
  name: "Ananya Nair",
  phone: "+91 98765 43210",
  email: "ananya@example.com",
  city: "Kochi",
  preferredAreas: ["Edappally", "Kakkanad"],
  categories: ["Hospitality", "Retail"],
  skills: ["Customer service", "POS billing", "English", "Teamwork"],
  experienceYears: 2,
  education: "Higher Secondary",
  languages: ["Malayalam", "English", "Hindi"],
  salaryExpectation: 20000,
  shifts: ["Day", "Flexible"],
  employmentTypes: ["Full-time"],
  workModes: ["On-site", "Hybrid"],
  relocationAllowed: false,
  available: true,
  resumeName: "Ananya-Nair-Resume.pdf",
  profileCompletion: 92,
  termsAccepted: true,
};

export const initialDemoState: DemoState = {
  jobs,
  candidate,
  matches: calculateMatches(jobs, candidate),
  applications: [],
  notifications: [
    {
      id: "notification-1",
      role: "candidate",
      title: "A new job matches your profile",
      body: "Restaurant Service Associate in Kochi is a strong match.",
      createdAt: "2026-07-15T10:15:00.000Z",
      read: false,
    },
    {
      id: "notification-2",
      role: "employer",
      title: "Job submitted for review",
      body: "Kitchen Helper is now in the admin approval queue.",
      createdAt: "2026-07-16T04:21:00.000Z",
      read: false,
    },
  ],
  auditEvents: [
    {
      id: "audit-1",
      action: "Job approved",
      target: "JOB-2407",
      actor: "Priya · Admin",
      createdAt: "2026-07-14T11:00:00.000Z",
    },
  ],
  legalDocuments: [
    { id: "legal-privacy-1", name: "Privacy Notice", version: "v1.0", audience: "Employee & employer", status: "published", publishedAt: "2026-07-12T08:00:00.000Z", content: "Explains what personal data Alpha Consultancy collects, why it is processed, and how users exercise their rights." },
    { id: "legal-candidate-1", name: "Employee Terms", version: "v1.0", audience: "Employee", status: "published", publishedAt: "2026-07-12T08:05:00.000Z", content: "Covers employee responsibilities, screening, consent, and interview handoff." },
    { id: "legal-employer-1", name: "Employer Data-Use Terms", version: "v1.0", audience: "Employer", status: "published", publishedAt: "2026-07-12T08:10:00.000Z", content: "Restricts candidate data to approved recruitment purposes." },
    { id: "legal-application-1", name: "Application Consent", version: "v1.0", audience: "Employee", status: "published", publishedAt: "2026-07-12T08:15:00.000Z", content: "Allows Alpha Consultancy to screen a profile for one selected job." },
    { id: "legal-handoff-1", name: "Interview Handoff Consent", version: "v1.0", audience: "Employee", status: "published", publishedAt: "2026-07-12T08:20:00.000Z", content: "Authorizes identity and resume sharing with one verified employer." },
  ],
  dataRequests: [],
  employerVerification: {
    status: "under_review",
    notes: "Organization submitted. Admin checks are in progress.",
    updatedAt: "2026-07-12T08:30:00.000Z",
    submittedAt: "2026-07-12T08:30:00.000Z",
    checks: { registration: false, contact: false, dataUseTerms: true },
  },
};
